sudo ml startMount.sh sm
sudo ml repo/repo rp
sudo ml repo/run.sh rpr
sudo ml cmdList.sh cl
sudo ml showTmpContent.sh tmp
sudo ml write2Tmp.sh wtmp
sudo ml changeSwapMem.sh mem
sudo ml setProxy.sh proxy
sudo ml cmdListCreate.sh clc
sudo ml repo/mountImage.sh mi
sudo ml cleanDocker.sh cleard
sudo ml startChrome.sh chrome
sudo ml startRedroid.sh re
