sudo ml startMount.sh sm
sudo ml repo/repo rp
sudo ml repo/run.sh rpr
sudo ml cmdList.sh cl
sudo ml showTmpContent.sh tmp
sudo ml write2Tmp.sh wtmp
sudo ml changeSwapMem.sh mem
sudo ml setProxy.sh proxy
sudo ml cmdListCreate.sh clc
sudo ml repo/mountImage.sh mi
sudo ml cleanDocker.sh cleard
sudo ml startChrome.sh chrome
sudo ml startRedroid.sh re
sudo ml jupyter.sh jp
sudo ml startWineProxy.sh wp
sudo ml startNaifu.sh nf
sudo ml mountWin.sh mw
sudo ml tencent.sh tx
sudo ml sadtalk.sh sd
sudo ml matv2.sh mat
sudo ml pwd.sh hello
sudo ml soVitsSvc.sh so
sudo ml bringToLife.sh br
sudo ml nvidia.sh nv
sudo ml makeittalk.sh mt
sudo ml listWebrtc.sh lw
sudo ml wLw.sh wlw
sudo ml pose.sh pose
sudo ml panoHead.sh pano
sudo ml resetNet.sh rn
sudo ml reclone.sh rcs
